modLoader="javafml" 
loaderVersion="${loader_version_range}"
issueTrackerURL="https://github.com/owmii/lost-trinkets/issues"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
displayURL="https://www.curseforge.com/minecraft/mc-mods/lost-trinkets"
authors="${mod_authors}"
description='''
${mod_description}
'''

[[dependencies.${mod_id}]]
    modId="lollipop"
    mandatory=true
    versionRange="${lollipop_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
